defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: post
      toc: true
excerpt_separator: <!--more-->
highlighter: rouge
permalink: /:categories/:title